apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: flux-demo-product-001
  labels:
    backup.apiconnect.ibm.com/component: product
  namespace: apim-demo-001
spec:
  state: Published
  definition:
    product: 1.0.0
    info:
      title: flux-demo-product-001
      name: flux-demo-product-001
      version: '001'
    plans:
      default-plan:
        rate-limits:
          default:
            value: 100/1hour
        title: Default Plan
        description: Default Plan
        approval: false
  apis:
    apis:
      - name: flux-demo-api-001
      - name: flux-demo-api-002
  share:
    apim:
      credentialsSecret: apim-credentials
      providerOrg: api-demo-001-porg
      catalog: sandbox