apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  labels:
    backup.apiconnect.ibm.com/component: api
  name: flux-demo-api-002
  namespace: apim-demo-001
spec:
  definition:
    configMap: ''
    external:
      url: https://thesstorage.blob.core.windows.net/petstore/petstore-swagger-without-security-definitions.json
    properties:
      title: flux-demo-api-002
      version: "002"